# This file is generated by make_xlat_tree.
# All changes made in this file will be lost.

xlat_tree = {
    '\xc3': ["", {
        '\x80': ["A", None],
        '\x81': ["A", None],
        '\x82': ["I", None],
        '\x83': ["A", None],
        '\x84': ["A", None],
        '\x85': ["O", None],
        '\x86': ["A", None],
        '\x87': ["S", None],
        '\x88': ["E", None],
        '\x89': ["E", None],
        '\x8a': ["E", None],
        '\x8b': ["Yo", None],
        '\x8c': ["I", None],
        '\x8d': ["I", None],
        '\x8e': ["I", None],
        '\x92': ["O", None],
        '\x93': ["U", None],
        '\x94': ["O", None],
        '\x95': ["O", None],
        '\x96': ["O", None],
        '\x98': ["O", None],
        '\x99': ["U", None],
        '\x9a': ["U", None],
        '\x9b': ["U", None],
        '\x9c': ["U", None],
        '\x9f': ["ss", None],
        '\xa0': ["a", None],
        '\xa1': ["a", None],
        '\xa2': ["i", None],
        '\xa3': ["a", None],
        '\xa4': ["a", None],
        '\xa5': ["o", None],
        '\xa6': ["a", None],
        '\xa7': ["s", None],
        '\xa8': ["e", None],
        '\xa9': ["e", None],
        '\xaa': ["e", None],
        '\xab': ["yo", None],
        '\xac': ["i", None],
        '\xad': ["i", None],
        '\xae': ["i", None],
        '\xb2': ["o", None],
        '\xb3': ["u", None],
        '\xb4': ["o", None],
        '\xb5': ["o", None],
        '\xb6': ["o", None],
        '\xb8': ["o", None],
        '\xb9': ["u", None],
        '\xba': ["u", None],
        '\xbb': ["u", None],
        '\xbc': ["u", None]
    }],
    '\xc4': ["", {
        '\x82': ["A", None],
        '\x83': ["a", None],
        '\x84': ["O", None],
        '\x85': ["o", None],
        '\x86': ["Ch", None],
        '\x87': ["ch", None],
        '\x98': ["E", None],
        '\x99': ["e", None]
    }],
    '\xc5': ["", {
        '\x81': ["W", None],
        '\x82': ["w", None],
        '\x83': ["Ny", None],
        '\x84': ["ny", None],
        '\x9a': ["Sh", None],
        '\x9b': ["sh", None],
        '\xa0': ["Sh", None],
        '\xa1': ["sh", None],
        '\xb9': ["Zh", None],
        '\xba': ["zh", None],
        '\xbb': ["Zh", None],
        '\xbc': ["zh", None],
        '\xbd': ["S", None],
        '\xbe': ["s", None]
    }],
    '\xc8': ["", {
        '\x98': ["Sh", None],
        '\x99': ["sh", None],
        '\x9a': ["Ts", None],
        '\x9b': ["ts", None]
    }],
    '\xd0': ["", {
        '\x81': ["Yo", None],
        '\x84': ["Ye", None],
        '\x86': ["I", {
            '\xcc': ["", {
                '\x88': ["Yi", None]
            }]
        }],
        '\x87': ["Yi", None],
        '\x90': ["A", None],
        '\x91': ["B", None],
        '\x92': ["V", None],
        '\x93': ["G", None],
        '\x94': ["D", None],
        '\x95': ["E", {
            '\xcc': ["", {
                '\x88': ["Yo", None]
            }]
        }],
        '\x96': ["Zh", None],
        '\x97': ["Z", None],
        '\x98': ["I", {
            '\xcc': ["", {
                '\x86': ["J", None]
            }]
        }],
        '\x99': ["J", None],
        '\x9a': ["K", None],
        '\x9b': ["L", None],
        '\x9c': ["M", None],
        '\x9d': ["N", None],
        '\x9e': ["O", None],
        '\x9f': ["P", None],
        '\xa0': ["R", None],
        '\xa1': ["S", None],
        '\xa2': ["T", None],
        '\xa3': ["U", None],
        '\xa4': ["F", None],
        '\xa5': ["Kh", None],
        '\xa6': ["Ts", None],
        '\xa7': ["Ch", None],
        '\xa8': ["Sh", None],
        '\xa9': ["Sch", None],
        '\xaa': ["'", None],
        '\xab': ["Y", None],
        '\xac': ["", None],
        '\xad': ["E", None],
        '\xae': ["Yu", None],
        '\xaf': ["Ya", None],
        '\xb0': ["a", None],
        '\xb1': ["b", None],
        '\xb2': ["v", None],
        '\xb3': ["g", None],
        '\xb4': ["d", None],
        '\xb5': ["e", {
            '\xcc': ["", {
                '\x88': ["yo", None]
            }]
        }],
        '\xb6': ["zh", None],
        '\xb7': ["z", None],
        '\xb8': ["i", {
            '\xcc': ["", {
                '\x86': ["j", None]
            }]
        }],
        '\xb9': ["j", None],
        '\xba': ["k", None],
        '\xbb': ["l", None],
        '\xbc': ["m", None],
        '\xbd': ["n", None],
        '\xbe': ["o", None],
        '\xbf': ["p", None]
    }],
    '\xd1': ["", {
        '\x80': ["r", None],
        '\x81': ["s", None],
        '\x82': ["t", None],
        '\x83': ["u", None],
        '\x84': ["f", None],
        '\x85': ["kh", None],
        '\x86': ["ts", None],
        '\x87': ["ch", None],
        '\x88': ["sh", None],
        '\x89': ["sch", None],
        '\x8a': ["'", None],
        '\x8b': ["y", None],
        '\x8c': ["", None],
        '\x8d': ["e", None],
        '\x8e': ["yu", None],
        '\x8f': ["ya", None],
        '\x91': ["yo", None],
        '\x94': ["ye", None],
        '\x96': ["i", {
            '\xcc': ["", {
                '\x88': ["yi", None]
            }]
        }],
        '\x97': ["yi", None]
    }],
    '\xd2': ["", {
        '\x90': ["G", None],
        '\x91': ["g", None]
    }],
    '\xe1': ["", {
        '\xba': ["", {
            '\x9e': ["Ss", None]
        }]
    }],
    '\xe2': ["", {
        '\x80': ["", {
            '\x98': ["'", None],
            '\x99': ["'", None]
        }]
    }],
    '\x41': ["", {
        '\xcc': ["", {
            '\x80': ["A", None],
            '\x81': ["A", None],
            '\x82': ["I", None],
            '\x83': ["A", None],
            '\x86': ["A", None],
            '\x88': ["A", None],
            '\x8a': ["O", None]
        }]
    }],
    '\x43': ["", {
        '\xcc': ["", {
            '\xa7': ["S", None]
        }]
    }],
    '\x45': ["", {
        '\xcc': ["", {
            '\x80': ["E", None],
            '\x81': ["E", None],
            '\x82': ["E", None]
        }]
    }],
    '\x49': ["", {
        '\xcc': ["", {
            '\x80': ["I", None],
            '\x81': ["I", None],
            '\x82': ["I", None],
            '\x88': ["Yi", None]
        }]
    }],
    '\x4e': ["", {
        '\xcc': ["", {
            '\x83': ["N", None]
        }]
    }],
    '\x4f': ["", {
        '\xcc': ["", {
            '\x80': ["O", None],
            '\x81': ["O", None],
            '\x82': ["O", None],
            '\x88': ["O", None]
        }]
    }],
    '\x53': ["", {
        '\xcc': ["", {
            '\xa7': ["Sh", None]
        }]
    }],
    '\x54': ["", {
        '\xcc': ["", {
            '\xa7': ["Ts", None]
        }]
    }],
    '\x55': ["", {
        '\xcc': ["", {
            '\x80': ["U", None],
            '\x81': ["U", None],
            '\x82': ["U", None],
            '\x88': ["U", None]
        }]
    }],
    '\x61': ["", {
        '\xcc': ["", {
            '\x80': ["a", None],
            '\x81': ["a", None],
            '\x82': ["i", None],
            '\x83': ["a", None],
            '\x86': ["a", None],
            '\x88': ["a", None],
            '\x8a': ["o", None]
        }]
    }],
    '\x63': ["", {
        '\xcc': ["", {
            '\xa7': ["s", None]
        }]
    }],
    '\x65': ["", {
        '\xcc': ["", {
            '\x80': ["e", None],
            '\x81': ["e", None],
            '\x82': ["e", None]
        }]
    }],
    '\x69': ["", {
        '\xcc': ["", {
            '\x80': ["i", None],
            '\x81': ["i", None],
            '\x82': ["i", None],
            '\x88': ["yi", None]
        }]
    }],
    '\x6e': ["", {
        '\xcc': ["", {
            '\x83': ["n", None]
        }]
    }],
    '\x6f': ["", {
        '\xcc': ["", {
            '\x80': ["o", None],
            '\x81': ["o", None],
            '\x82': ["o", None],
            '\x88': ["o", None]
        }]
    }],
    '\x73': ["", {
        '\xcc': ["", {
            '\xa7': ["sh", None]
        }]
    }],
    '\x74': ["", {
        '\xcc': ["", {
            '\xa7': ["ts", None]
        }]
    }],
    '\x75': ["", {
        '\xcc': ["", {
            '\x80': ["u", None],
            '\x81': ["u", None],
            '\x82': ["u", None],
            '\x88': ["u", None]
        }]
    }]
}
