# This file is generated by make_xlat_tree.
# All changes made in this file will be lost.

xlat_tree = {
    '\xc3': ["", {
        '\x80': ["A", None],
        '\x81': ["a", None],
        '\x84': ["A", None],
        '\x85': ["O", None],
        '\x89': ["E", None],
        '\x8b': ["Yo", None],
        '\x93': ["U", None],
        '\x96': ["O", None],
        '\xa0': ["a", None],
        '\xa1': ["a", None],
        '\xa4': ["a", None],
        '\xa5': ["o", None],
        '\xa9': ["e", None],
        '\xab': ["yo", None],
        '\xb3': ["u", None],
        '\xb6': ["o", None]
    }],
    '\xc4': ["", {
        '\x84': ["O", None],
        '\x85': ["o", None],
        '\x86': ["Ch", None],
        '\x87': ["ch", None],
        '\x98': ["E", None],
        '\x99': ["e", None]
    }],
    '\xc5': ["", {
        '\x81': ["W", None],
        '\x82': ["w", None],
        '\x83': ["Ny", None],
        '\x84': ["ny", None],
        '\x9a': ["Sh", None],
        '\x9b': ["sh", None],
        '\xa0': ["Sh", None],
        '\xa1': ["sh", None],
        '\xb9': ["Zh", None],
        '\xba': ["zh", None],
        '\xbb': ["Zh", None],
        '\xbc': ["zh", None],
        '\xbd': ["S", None],
        '\xbe': ["s", None]
    }],
    '\xd0': ["", {
        '\x81': ["Yo", None],
        '\x90': ["A", None],
        '\x91': ["B", None],
        '\x92': ["V", None],
        '\x93': ["G", None],
        '\x94': ["D", None],
        '\x95': ["E", {
            '\xcc': ["", {
                '\x88': ["Yo", None]
            }]
        }],
        '\x96': ["Zh", None],
        '\x97': ["Z", None],
        '\x98': ["I", {
            '\xcc': ["", {
                '\x86': ["J", None]
            }]
        }],
        '\x99': ["J", None],
        '\x9a': ["K", None],
        '\x9b': ["L", None],
        '\x9c': ["M", None],
        '\x9d': ["N", None],
        '\x9e': ["O", None],
        '\x9f': ["P", None],
        '\xa0': ["R", None],
        '\xa1': ["S", None],
        '\xa2': ["T", None],
        '\xa3': ["U", None],
        '\xa4': ["F", None],
        '\xa5': ["Kh", None],
        '\xa6': ["Ts", None],
        '\xa7': ["Ch", None],
        '\xa8': ["Sh", None],
        '\xa9': ["Sch", None],
        '\xaa': ["'", None],
        '\xab': ["Y", None],
        '\xac': ["", None],
        '\xad': ["E", None],
        '\xae': ["Yu", None],
        '\xaf': ["Ya", None],
        '\xb0': ["a", None],
        '\xb1': ["b", None],
        '\xb2': ["v", None],
        '\xb3': ["g", None],
        '\xb4': ["d", None],
        '\xb5': ["e", {
            '\xcc': ["", {
                '\x88': ["yo", None]
            }]
        }],
        '\xb6': ["zh", None],
        '\xb7': ["z", None],
        '\xb8': ["i", {
            '\xcc': ["", {
                '\x86': ["j", None]
            }]
        }],
        '\xb9': ["j", None],
        '\xba': ["k", None],
        '\xbb': ["l", None],
        '\xbc': ["m", None],
        '\xbd': ["n", None],
        '\xbe': ["o", None],
        '\xbf': ["p", None]
    }],
    '\xd1': ["", {
        '\x80': ["r", None],
        '\x81': ["s", None],
        '\x82': ["t", None],
        '\x83': ["u", None],
        '\x84': ["f", None],
        '\x85': ["kh", None],
        '\x86': ["ts", None],
        '\x87': ["ch", None],
        '\x88': ["sh", None],
        '\x89': ["sch", None],
        '\x8a': ["'", None],
        '\x8b': ["y", None],
        '\x8c': ["", None],
        '\x8d': ["e", None],
        '\x8e': ["yu", None],
        '\x8f': ["ya", None],
        '\x91': ["yo", None]
    }]
}
